gesdinet_jwt_refresh_token:
    refresh_token_class: Domain\Security\Jwt\RefreshToken
    ttl_update: true
    ttl: 2592000 # a month
    return_expiration: true
    token_parameter_name: refresh_token
    return_expiration_parameter_name: refresh_token_expiration_timestamp
