when@dev:
    web_profiler:
        toolbar: true
        excluded_ajax_paths: '^/(build/|@vite/|@react-refresh)'

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
